services:
  # Kafka broker running in KRaft mode (no ZooKeeper)
  # Handles message streaming and event storage
  # Exposes ports:
  # - 9092: Kafka broker
  # - 9093: Kafka controller
  # - 9015: JMX monitoring
  kafka:
    container_name: kafka-kraft
    image: quay.io/debezium/kafka:latest
    ports:
      - 9092:9092
      - 9093:9093
      - 9015:9015
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - BROKER_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - NODE_ROLE=broker,controller
      - ADVERTISED_HOST_NAME=172.29.208.1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - debezium-network

  # Debezium Connect service
  # Runs the Debezium connectors for CDC (Change Data Capture)
  # Includes Oracle instant client for Oracle CDC
  # Exposes port 8083 for REST API
  debezium:
    container_name: debezium
    image:  quay.io/debezium/connect:latest
    ports:
      - 8083:8083
    depends_on:
      - kafka
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - LD_LIBRARY_PATH=/instant_client
      - KAFKA_DEBUG=true
      - DEBUG_SUSPEND_FLAG=n
      - JAVA_DEBUG_PORT=0.0.0.0:5005
    networks:
      - debezium-network

  # Web UI for monitoring Kafka
  # Provides visualization of topics, brokers, messages
  # Accessible at http://localhost:8081
  kafka-ui:
    container_name: kafka-dash
    image: ghcr.io/kafbat/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - debezium-network

  # Oracle Database (Source)
  # Free version of Oracle Database for CDC source
  # Runs with archive logging enabled for CDC
  # Exposes port 1521 for SQL*Net listener
  # Includes initialization scripts for setup
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    restart: unless-stopped
    ports:
      - "1521:1521"   # Oracle Listener
    environment:
      ORACLE_PWD: "top_secret" # Initial SYS/SYSTEM password
      ORACLE_SID: "FREE"
      ENABLE_ARCHIVELOG: "true"
    volumes:
      - oracle_data:/opt/oracle/oradata  # Persist data
      - ./oracle-initialize.sh:/home/oracle/oracle-initialize.sh
      - ./oracle_logminer-setup.sh:/home/oracle/oracle_logminer-setup.sh
      - ./oracle-load-data.sql:/home/oracle/oracle-load-data.sql
    networks:
      - debezium-network

  # PostgreSQL Database (Sink)
  # Target database for CDC replication
  # Exposes port 5432 for PostgreSQL connections
  # Connect using: docker exec -it postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
  postgres:
    # *-----------------------------*
    # To connect to the DB:
    #   docker exec -it postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
    # *-----------------------------*
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - debezium-network

  # Debezium UI
  # Web interface for managing Debezium connectors
  # Accessible at http://localhost:8082
  # Provides UI for configuring and monitoring CDC connectors
  debezium-ui:
    container_name: debezium-ui
    image: quay.io/debezium/debezium-ui:latest
    ports:
      - "8082:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://debezium:8083
    depends_on:
      - debezium
    networks:
      - debezium-network

# Bridge network for container communication
networks:
  debezium-network:
    driver: bridge

# Persistent volumes for data storage
volumes:
  kafka_data:
  oracle_data: